/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: f802deecd93955467b1273d94678fb5e)
interface __BaseEnv_Env {
  MYBROWSER: BrowserRun;
  NTFY_TOPIC: "hitl-captcha-alerts";
  X402_NETWORK: "eip155:84532";
  X402_PRICE: "$0.25";
  SESSION_TTL_SECONDS: "900";
  CAPTCHA_SESSION: DurableObjectNamespace<import("./src/index").CaptchaSession>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "CaptchaSession";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      "NTFY_TOPIC" | "X402_NETWORK" | "X402_PRICE" | "SESSION_TTL_SECONDS"
    >
  > {}
}
